# Generated by Django 3.2.5 on 2021-09-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('ItemID', models.AutoField(primary_key=True, serialize=False)),
                ('StockId', models.IntegerField()),
                ('ItemType', models.CharField(max_length=500)),
                ('ItemName', models.CharField(max_length=500)),
                ('BrandName', models.CharField(max_length=500)),
                ('Quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('StockID', models.AutoField(primary_key=True, serialize=False)),
                ('StockType', models.CharField(max_length=500)),
                ('SupplierID', models.IntegerField()),
                ('DateOfRecieved', models.DateField()),
            ],
        ),
    ]
